vmware/terraform-provider-vcf

.github/workflows/issues.yml, .github/workflows/lock.yml, .github/workflows/pull-requests.yml, .github/workflows/stale.yml
Pin actions to a full length commit SHA.
Ref: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
=> chore(gha): pin actions to commit sha

internal/validation/validation_utils.go
Signed-off-by: Bryan Heden <b.heden@gmail.com>
This offers a fix during vcf_domain creation when defining an nfs_datastore. The validation_utils.IsEmpty function doesn't check properly for a boolean value. This could also fix potential bugs in a few other places.
https://github.com/vmware/terraform-provider-vcf/blob/v0.2.0/internal/datastores/nfs_datastore_subresource.go#L68-L72
**Breaking …
=> validation_utils IsEmpty doesn't check for boolean values

internal/provider/resource_cluster.go, internal/provider/resource_domain.go, internal/provider/resource_domain_test.go
The domain update logic failed to do a refresh (read) just after the update operation has completed. This resulted in failing acceptance test, the fix to which was simple: execute a read at the end of domain update method. Some function parameter order was messed up.
Additionally, the Domain E2E test was expanded with:
Add a second cluster,
Add a forth host in the additional cluster,
Remove the forth host,
Remove the additional cluster
This way all update operations, currently supported for domain are tested.
Also optimise domain E2E test resource usage.
Testing done:
make lint
make build
make test
=== RUN   TestAccResourceVcfDomain
=== …
=> Fix domain update and expand E2E

CHANGELOG.md, docs/resources/cluster.md, docs/resources/domain.md, internal/cluster/cluster_operations.go, internal/network/ip_address_pool_subresource.go, internal/network/nsx_subresource.go, internal/provider/resource_cluster.go, internal/provider/resource_cluster_test.go, internal/validation/validation_utils.go, internal/validation/validation_utils_test.go
Introduced  E2E test TestAccResourceVcfClusterCreate, which has a smaller footprint than the TestAccResourceVcfCluster, now renamed to TestAccResourceVcfClusterFull. Added an ip_address_pool attribute to the cluster tests. Navigated to NSX UI and observed "static-ip-pool-01" present under Networking -> IP Address Pools.
Fix indentation in the nsx_subresource.go's "form_factor" attribute definition, that was cryptically reported by the linter
Issue Number: #54 
**Test and …
=> feat: add support for ip pool range creation during cluster/domain creation

internal/nsx_edge_cluster/edge_node_subresource.go, internal/provider/resource_edge_cluster.go
The upper limit that the SDDC manager enforces on ASN values is 2^32 (4294967295).
In our code this is evaluated by raising 2 to the power of 32 and trying to cast it into the default integer.
On systems where Golang's integer defaults to 32-bit signed this cannot be enforced since it will overflow and actually produce a negative value.
Even if we change the validation util to work with int64 the input values would theoretically overflow since Terraform's integer inputs use the default int type.
Closes #120
=> Redefine the upper boundary for Edge Cluster and Edge Node ASN setting

internal/provider/resource_vcf_instance_test.go, internal/sddc/sddc_nsx_subresource.go
The ip pool configuration is being omitted from the specification when configuring NSX.
I am populating IPAddressPoolSpec if "ip_address_pool" is set before issuing API call.
https://github.com/vmware/terraform-provider-vcf/issues/113
=> Respect IP Pool configuration for NSX subresource

go.mod, go.sum
Bump vcf-sdk-go to v0.2.3
Closes #128
=> chore(depa): bump vcf-sdk-go to v0.2.3

examples/resources/edge_cluster/variables.tf, examples/resources/edge_cluster/vcf_edge_cluster.tf
Fixes incorrect keys and variables in edge cluster example.
Closes #131
Ran "terraform plan" on the example configuration to make sure there are no more typo's and incorrect keys
=> fix: rename incorrect property in edge node example

internal/cluster/cluster_operations.go
The option to create a cluster with a predefined vLCM image is implemented but doesn't work due to a simple string mismatch
=> Fix cluster creation with a vLCM image

docs/resources/edge_cluster.md, docs/resources/network_pool.md, go.mod, go.sum, internal/nsx_edge_cluster/edge_cluster_operations.go, internal/nsx_edge_cluster/edge_node_subresource.go, internal/provider/resource_edge_cluster.go, internal/provider/resource_edge_cluster_test.go, internal/provider/resource_network_pool.go
This PR contains 4 changes
1. Tier 0 and Tier 1 routers are now optional for Edge Clusters. 
Several other properties that are only required when a Tier 0 router is configured are also being marked as optional.
2. I'm adding new properties to Edge nodes for configuring a new management network for new nodes.
These are optional. I am not including them in the acceptance tests since they complicate the testing setup.
3. I'm fixing the VLAN ID for network pools. 0 is now a valid and accepted value.
4. I'm fixing "skip_tep_routability_check" which is currently being ignored
Closes #177
Closes #175
Closes #147
Ran `TestAccResourceEdgeCluster` and …
=> Configure optional properties for edge clusters and nodes

docs/resources/instance.md, internal/provider/resource_vcf_instance_test.go, internal/sddc/sddc_cluster_subresource.go
Enable VUM-based bringup via `resource_vcf_instance`.
I am adding a new property `cluster_image_enabled` which when set to `false` disables vLCM when deploying a management domain.
The default value inferred by the API for this property is `true`.
Closes #151
Ran `TestAccResourceVcfSddcBasic`
I did a minor fix to the test that I forgot to submit along with the SDK upgrade.
The secondary DNS can no longer match the primary DNS and the API fails in VCF 5.X
To resolve this I've simply removed the secondary DNS from the test since it's optional
`resource_vcf_instance` will stop working for 4.x releases since …
=> feat: enable vum-based bringup via `r/vcf_instance`

docs/resources/cluster.md, docs/resources/edge_cluster.md, docs/resources/host.md, internal/constants/constants.go, internal/nsx_edge_cluster/edge_cluster_operations.go, internal/nsx_edge_cluster/edge_node_subresource.go, internal/provider/resource_cluster.go, internal/provider/resource_cluster_test.go, internal/provider/resource_edge_cluster.go, internal/provider/resource_edge_cluster_test.go, internal/provider/resource_host.go, internal/provider/resource_host_test.go
Accepting entity identifiers as inputs is convenient when these entities are managed by Terraform but not so much when they are created externally.
I'm modifying the resource schemas for hosts, clusters and edge clusters so that they accept network pool names, domain names and compute cluster names respectively in addition to their IDs.
Setting values for both attributes at the same time is not allowed and will result in an explicit error.
Closes #91
Closes #191
Closes #193
Since this change introduces new API calls I've added additional test cases or modified existing ones where appropriate
`TestAccResourceVcfClusterCreate` -> modified to use domain …
=> feat: accept entity names as inputs for several resources

docs/resources/csr.md, internal/certificates/certificate_operations.go, internal/constants/constants.go, internal/provider/resource_certificate.go, internal/provider/resource_certificate_test.go, internal/provider/resource_csr.go, internal/provider/resource_csr_test.go, internal/provider/resource_external_certificate.go
The resource for generating certificate signing requests accepts a resource type and automatically determines the correct FQDN for the request. This only works for resources of type VCENTER due to a limitation in the underlying API.
To resolve this we have to switch to an API andpoint that returns the full set of possible resources. Unfortunately in 5.1.1 this is not possible because this endpoint is not public.
A public endpoint will be available in an upcoming VCF release.
But even if we wait and try to fix this later we would encounter another problem. Some resources can have multiple instances (NSX for example). It would not be possible for the provider to determine which FQDN to use.
The only complete solution would be to explicitly provide the FQDN for …
=> feat: add `fqdn` parameter for `r/csr`

go.mod, go.sum, internal/sddc/sddc_vsan_subresource.go
Support for configuring vSAN in ESA mode was added in VCF 5.
It was implemented as an optional attribute with https://github.com/vmware/terraform-provider-vcf/pull/190
The flaw in my original PR is that the new property is optional and since it is marked with "omitempty" it is skipped during serialization whenever it is set to false.
I've made a change to the SDK that marks the property as required. The containing structure is still optional.
This means that `esa_enabled` will now behave as follows:
* When `esa_enabled = true` the `VSANEsaConfig` structure will be set and vSAN will be configured in ESA mode
* When `esa_enabled = false` the `VSANEsaConfig` structure will be set and vSAN will be configured in normal mode
* When `esa_enabled` is not set  the …
=> fix: esa_enabled for r/vcf_instance

internal/credentials/constants.go
This pull request is to add the missed vrops resourceType definition in resource/credentials
Issue Number: [218](https://github.com/vmware/terraform-provider-vcf/issues/218)
=> add missed vrops resourcetype for credentials

internal/provider/data_credentials_test.go, internal/provider/data_network_pool.go, internal/provider/data_network_pool_test.go, internal/provider/data_source_cluster_test.go, internal/provider/data_source_domain_test.go, internal/provider/provider_test.go, internal/provider/resource_ceip_test.go, internal/provider/resource_certificate_authority_test.go, internal/provider/resource_certificate_test.go, internal/provider/resource_cluster_personality_test.go, internal/provider/resource_cluster_test.go, internal/provider/resource_credentials_auto_rotate_policy_test.go, internal/provider/resource_credentials_password_rotate_test.go, internal/provider/resource_credentials_password_update_test.go, internal/provider/resource_csr_test.go, internal/provider/resource_domain_test.go, internal/provider/resource_edge_cluster_test.go, internal/provider/resource_external_certificate_test.go, internal/provider/resource_host_test.go, internal/provider/resource_network_pool_test.go, internal/provider/resource_user_test.go, internal/provider/resource_vcf_instance_test.go
Some acceptance tests fail if they try to use a resource that is already migrated to the framework.
Right now the only such resource is `vcf_network_pool`. To resolve this I've modified all tests to bootstrap
the provider in muxed mode so that all resources are available.
=> fix: bootstrap in muxed mode during testing

internal/provider/provider.go
Updates the provider configuration to address the issue where the function assumes the configuration is for Cloud Builder if the SDDC Manager username is not provided.
Added a check to ensure that at least one of the configurations is provided. If neither is provided, we can return an appropriate error message.
Closes #238
=> fix: provider configuration validation

internal/api_client/sddc_manager_client.go, internal/certificates/certificate_operations.go, internal/credentials/credential_operations.go, internal/provider/resource_ceip.go, internal/provider/resource_certificate.go, internal/provider/resource_cluster.go, internal/provider/resource_cluster_personality.go, internal/provider/resource_csr.go, internal/provider/resource_domain.go, internal/provider/resource_edge_cluster.go, internal/provider/resource_external_certificate.go, internal/provider/resource_host.go
An enchanced task tracker was added in [#227](https://github.com/vmware/terraform-provider-vcf/pull/227).
This PR plugs it into the codebase in the place of the existing task tracking functions.
To summarize the features of the new tracker:
It supports:
1. Sub-task message logging
2. Main task message logging
3. Custom polling interval configuration (see r/host for example). Some resources may benefit from frequent console updates.
It does not support
1. Task retrying. In my experience this has never worked and is not necessary.
Not because there is …
=> feat: integrate new task tracker

README.md, docs/index.md, docs/resources/edge_cluster.md, go.mod, go.sum, internal/nsx_edge_cluster/edge_cluster_operations.go, internal/nsx_edge_cluster/edge_node_subresource.go, internal/provider/resource_ceip.go, internal/provider/resource_edge_cluster.go, internal/provider/resource_edge_cluster_test.go
This PR consumes the latest SDK release (v0.5.0) which contains API support for VCF 5.2.1
an does not include any integration of new functionality that may be exposed by the new API.
Ran the tests for some of the "heavier" resources - domain, cluster, edge cluster
Some of the optional properties for edge clusters are now required. Due to this I also removed the "basic" edge …
=> chore(deps): bump SDK for vcf 5.2.1

CHANGELOG.md, internal/provider/resource_vcf_instance.go
Adds `8.0.3` to the allowed `dvSwitchVersion` to support vSphere 8.0 U3.
=> fix: add 8.0.3 to dvSwitchVersion

go.mod, go.sum
Bumps `bump golang.org/x/net` from v0.28.0 to v0.33.0 due to  CVE-2024-45338.
Ref: https://github.com/advisories/GHSA-w32m-9786-jp63
=> chore(deps): bump golang.org/x/net from v0.28.0 to v0.33.0

docs/resources/edge_cluster.md, internal/provider/resource_edge_cluster.go, internal/provider/resource_edge_cluster_test.go, internal/validation/validation_utils.go
Making Tier 0 router name optional again and relaxing ASN restrictions while preserving the range limit.
https://github.com/vmware/terraform-provider-vcf/issues/293
https://github.com/vmware/terraform-provider-vcf/issues/294
=> Relax Edge Cluster setting restrictions for Tier0/1 routers and ASN

docs/resources/edge_cluster.md, internal/provider/resource_edge_cluster.go, internal/provider/resource_edge_cluster_test.go
Marking `asn` and `routing_type` as optional inputs for edge clusters
=> feat: set asn and routing type as optional for edge clusters

docs/resources/credentials_rotate.md, docs/resources/credentials_update.md, internal/provider/resource_credentials_password_rotate.go, internal/provider/resource_credentials_password_update.go
Removes support for `once_only` in `r/credential`.
Closes #226
=> refactor: remove `once_only` in `r/credential`

internal/sddc/sddc_host_subresource.go
Do not transmit empty host subnet values when doing bringup.
The subnet setting is optional for hosts but the Cloud Builder API doesn't like receiving empty strings.
Closes #312
=> fix: host subresource ip allocation optional subnet

docs/resources/instance.md, internal/provider/resource_vcf_instance.go, internal/provider/resource_vcf_instance_test.go, internal/sddc/dvs_subresource.go, internal/sddc/sddc_vsan_subresource.go
Add missed parameters for vcf_instance resource
Issue Number: #335
=> fix: `vcf_instance` doesn't handle NSX enabled DVS with VCF 9.0

docs/resources/instance.md, internal/provider/resource_vcf_instance_test.go, internal/sddc/sddc_vcf_operations_collector_subresource.go
Updated values for `appliance_size` in `GetVcfOperationsCollectorSchema` to use those from `cfOperationsCollectorSpec`.
Ref: https://developer.broadcom.com/xapis/vcf-installer-api/9.0/data-structures/VcfOperationsCollectorSpec/index.html?scrollString=vcfOperationsCollectorSpec
=> fix: update values for `appliance_size`
