vmware/terraform-provider-vcf

- CHANGELOG.md
- docs/data-sources/cluster.md
- docs/resources/host.md
- examples/resources/cluster/vcf_cluster.tf
- examples/resources/domain/vcf_domain.tf
- internal/cluster/cluster_operations.go
- internal/provider/data_source_cluster.go
- internal/provider/data_source_cluster_test.go
- internal/provider/resource_cluster.go
- internal/provider/resource_cluster_test.go
- internal/provider/resource_host.go
- internal/provider/resource_host_test.go
Also introduce E2E test for Cluster Import and Host Import
NOTE: removed the attribute "host_id" from the Commissioned Host resource and replaced it with just "id" as per Terraform standard practice. This way users can refer to the Host UUID (in cluster host spec for example) with the standard "vcf_host.host1.id"
Include "domain_id" as attribute to both data source cluster and imported cluster.
Issue Number: #36 #49  …
> Implement Host import, fix Cluster import

- docs/resources/domain.md
- internal/network/nsx_subresource.go
> Add validation to NSX-T form_factor parameter.

- CHANGELOG.md
Testing done:
make build
make lint
make test
Preparing CHANGELOG.md for next release
> Preparing CHANGELOG.md for next release

- CHANGELOG.md
Update CHANGELOG.md for v0.6.0 release
> Update CHANGELOG.md for v0.6.0 release

- docs/resources/instance.md
- internal/provider/resource_vcf_instance.go
Testing done:
make test
make build
make lint
v8.0.0 is added as an acceptable input in the bringup scenario, however the provider has been designed to support VCF 4.5.2, so there are no guarantees that bringup on VCF 5.X.X will succeed.
Issue Number: #95 
> Add Distributed virtual switch v8.0.0 as accepted input

- CHANGELOG.md
Just adding a new entry in the changelog for 0.8.0
The new feature in this version is the added support for NSX Edge Clusters
> Update changelog for 0.8.0

- CHANGELOG.md
This minor release only includes bugfixes
> Update changelog for v0.8.1

- go.mod
- go.sum
This bump is required to pick up a fix in the SDK https://github.com/vmware/vcf-sdk-go/pull/37
> Bump vcf-sdk-go to v0.2.4

- docs/resources/edge_cluster.md
- internal/nsx_edge_cluster/edge_node_subresource.go
Remove BGP peer password requirement
Clients of VCF have a use-case where the BGP peer password is not used.
Issue Number: https://github.com/vmware/terraform-provider-vcf/issues/146
> Remove BGP peer password requirement

- README.md
- docs/index.md
Adding the supported VCF version to the docs
Closes #80
> chore: add supported versions to docs

- CHANGELOG.md
Adding an entry in the changelog for v0.8.5
> chore: Prepare changelog for v0.8.5

- docs/resources/instance.md
- examples/resources/instance/vcf_instance.tf
This change adds entries in the docs & examples about how a user can configure the Cloud Builder appliance
with Terraform
N/A
> Add docs for deploying the CB appliance with Terraform

- docs/index.md
This is a simple documentation update. I'm moving the maximum supported version from 4.5.2 to 5.1.1
> Update docs to reflect the latest supported version of VCF

- CHANGELOG.md
I'm just adding an entry to the changelog for 0.9.1
> chore: Prepare changelog for 0.9.1

- .github/workflows/release.yml
- .goreleaser.yml
- go.sum
Fixes the configuration for goreleaser v2 (6.0.0) per [the upgrade guide](https://goreleaser.com/blog/goreleaser-v2/).
Ran `goreleaser check` and corrected all errors reported by the tool
> chore(gh): goreleaser v2 configuration 

- CHANGELOG.md
Adding an entry to the changelog for v0.10.0
> chore: update changelog for v0.10.0

- docs/data-sources/credentials.md
- internal/credentials/constants.go
- internal/credentials/credential_data_subresource.go
- internal/provider/data_credentials.go
Updates the resource type for NSX Edges from `NSX_EDGE` to `NSXT_EDGE` per the API.
Closes #214 
> fix: update nsx edge resource type

- .golangci.yml
- go.mod
- go.sum
- internal/provider/resource_user.go
- internal/provider/resource_vcf_instance.go
Fixes items found by `golangci-lint`.
```console
terraform-provider-vcf on  chore/fix-linter-issues
➜ golangci-lint run
terraform-provider-vcf on  chore/fix-linter-issues
➜ 
```
> chore: fix linter issues

- internal/provider/framework_provider.go
- internal/provider/provider.go
Updates the provider param descriptions; otherwise `make documentation` will fail.
> chore: update provider param descriptions

- internal/provider/data_source_cluster.go
- internal/provider/data_source_domain.go
- internal/provider/resource_ceip_test.go
- internal/provider/resource_certificate.go
- internal/provider/resource_certificate_authority_test.go
- internal/provider/resource_cluster.go
- internal/provider/resource_cluster_test.go
- internal/provider/resource_domain_test.go
- internal/provider/resource_external_certificate.go
- internal/provider/resource_host.go
- internal/provider/resource_host_test.go
- internal/provider/resource_user_test.go
Update `apiClient` to be more concise, where applicable.
This is preferred in Go for its brevity and clarity.
> refactor: update apiClient

- CHANGELOG.md
Updates the `CHANGELOG.md` for the 0.11.0 release.
> chore: update `CHANGELOG.md`

- CHANGELOG.md
- README.md
- docs/index.md
> chore(release): v0.11.0

- go.mod
- go.sum
- internal/api_client/sddc_manager_client.go
- internal/api_client/sddc_manager_client_test.go
- internal/api_client/task_tracker.go
- internal/certificates/certificate_operations.go
- internal/cluster/cluster_operations.go
- internal/credentials/credential_operations.go
- internal/domain/domain_operations.go
- internal/network/nsx_subresource.go
- internal/nsx_edge_cluster/edge_cluster_operations.go
- internal/provider/data_network_pool.go
- internal/provider/data_source_domain.go
- internal/provider/resource_ceip.go
- internal/provider/resource_certificate.go
- internal/provider/resource_certificate_authority.go
- internal/provider/resource_cluster.go
- internal/provider/resource_cluster_personality.go
- internal/provider/resource_csr.go
- internal/provider/resource_domain.go
- internal/provider/resource_edge_cluster.go
- internal/provider/resource_external_certificate.go
- internal/provider/resource_host.go
- internal/provider/resource_network_pool.go
- internal/provider/resource_user.go
- internal/provider/resource_vcf_instance.go
Bumps the SDK to consume the new `GetBody()` method on every response model.
Modifies `GetResponseAs` to accept a custom interface, matched by every model, that can read the response body and status code.
> feat: simplify response handling

- .golangci.yml
Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
Reference: https://golangci-lint.run/usage/linters/#exportloopref
> chore: update golangci-lint

- CHANGELOG.md
- README.md
Updating changelog and readme in preparation for v0.12.0
> chore(release) v0.12.0

- CHANGELOG.md
Adding an entry to the changelog for v0.13.0
> chore(release) v0.13.0

- CHANGELOG.md
> chore(release): v0.15.0

- docs/index.md
- docs/install.md
Applies HCL formatting with `terrafmt`.
> docs: apply hcl formatting

- .github/workflows/issues.yml
- .github/workflows/lock.yml
- .github/workflows/pull-requests.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- Update permissions.
- Remove superfluous quotes.
- Rename test workflows.
> chore(gh): update workflows

- CHANGELOG.md
> chore(release): v0.16.0

- CHANGELOG.md
Adding an entry to the changelog for v0.17.0
> chore: add entry to changelog for v0.17.0

- README.md
- docs/index.md
Update version compatibility tables.
Issue Number: #345
> chore: update version compatibility

- docs/resources/domain.md
- docs/resources/instance.md
Updates component sizing for vCenter, NSX Manager, and VCF Operations.
Use consistent ordering and style.
Closes #347
> docs: update component sizing

- internal/cluster/cluster_operations.go
- internal/cluster/host_spec_subresource.go
- internal/datastores/vmfs_datastore_subresource.go
- internal/datastores/vsan_remote_datastore_cluster_subresource.go
- internal/network/ip_address_pool_subresource.go
- internal/network/vds_subresource.go
- internal/provider/data_host.go
Refactors how slices are initialized throughout the codebase, replacing slice literals with the `var` keyword for slice declarations. This change improves code clarity and consistency, especially when slices are being appended to in subsequent logic.
> refactor: slice initializations to var syntax

- internal/constants/constants.go
- internal/credentials/constants.go
Removed unused constants from `internal/constants/constants.go`.
> chore: remove unused constants
